
version: 2

models:
  - name: stg_local_bike_brands
    description: "This model contains brands sold by the local bike company."
    columns:
      - name: brand_id
        description: "The primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null

  - name: stg_local_bike_categories
    description: "This table contains the categories of bike proposed by  local bike."
    columns:
      - name: category_id
        description: "The primary key, unique identifier for each category"
        tests:
            - unique
            - not_null

  - name: stg_local_bike_customers
    description: "This model contains customers-related information, including where they live."
    columns:
      - name: customer_id
        description: "The primary key, unique identifier for each customer"
        tests:
            - unique
            - not_null

  - name: stg_local_bike_orders
    description: "This model contains information about orders placed by customers, including the status of each order."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: order_status
        description: "The current status of the order."
        tests:
          - accepted_values:
              name: accepted_values_order_status
              values: [1, 2, 3, 4]
      - name: customer_id
        description: "Foreign key linking the order to the customer who placed it."
        tests:
          - relationships:
              name: customer_id_id_foreign_key_in_stg_local_bike_orders
              to: ref('stg_local_bike_customers')
              field: customer_id

  - name: stg_local_bike_order_items
    description: "This model contains information about each item included in an order, including its price, quantity, and shipping cost."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              name: order_id_id_foreign_key_in_stg_local_bike_order_items
              to: ref('stg_local_bike_orders')
              field: order_id
      
  - name: stg_local_bike_products
    description: "This model contains details of products available for sale, primarily focusing on information about the product's volume and size."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null    
      - name: brand_id
        description: "Foreign key linking the product to the corresponding brand."
        tests:
          - relationships:
              name: brand_id_id_foreign_key_in_stg_local_bike_brands
              to: ref('stg_local_bike_brands')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the product to the corresponding category."
        tests:
          - relationships:
              name: category_id_id_foreign_key_in_stg_local_bike_categories
              to: ref('stg_local_bike_categories')
              field: category_id              

  - name: stg_local_bike_staffs
    description: "This model contains details of staffs."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff."
        tests:
            - unique
            - not_null    
      - name: store_id
        description: "Foreign key linking the staff to the corresponding store."
        tests:
          - relationships:
              name: staff_id_id_foreign_key_in_stg_local_bike_staffs
              to: ref('stg_local_bike_staffs')
              field: staff_id
      - name: manager_id
        description: "Foreign key linking the staff to the corresponding manager." 

  - name: stg_local_bike_stocks
    description: "This model contains the stock information for each product."
    columns:
      - name: store_id
        description: "The primary key, unique identifier for each store where the product is available"
        tests:
            - unique
            - not_null
      - name: product_id
        description: "The primary key, unique identifier for each product available in stock"
        tests:
            - unique
            - not_null

  - name: stg_local_bike_stores
    description: "This model contains stores where the products are sold."
    columns:
      - name: store_id
        description: "The primary key, unique identifier for each store"
        tests:
            - unique
            - not_null