
version: 2

models:
    - name: stg_local_bike_brands
      description: "This table contains the local bike brands name"
      columns:
          - name: brand_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: stg_local_bike_categories
      description: "This table contains the local bike categories name"
      columns:
          - name: category_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
